version: "3"

x-defaults: &defaults
  networks:
    - ${NETWORK_CONTAINER}
  env_file:
      - ./.env
  
services:
  web:
    container_name: ${WEB_NAME}
    build:
      context: .
      dockerfile: ./apps/${WEB_NAME}/Dockerfile
    image: web-next:latest
    restart: always
    <<: *defaults
    ports:
      - ${WEB_lOCAL_PORT}:${WEB_DOCKER_PORT} 
    # volumes:
    #   - ./apps/${WEB_NAME}:/app/${WEB_NAME}
    #   - /app/apps/${WEB_NAME}/node_modules

  api:
    container_name: ${API_NAME}
    build:
      context: .
      dockerfile: ./apps/${API_NAME}/Dockerfile
    image: api-nest:latest
    <<: *defaults   
    restart: always
    ports:
      - ${API_LOCAL_PORT}:${API_DOCKER_PORT}
    # volumes:
    #   - ./apps/${API_NAME}/:/app/{API_NAME}
    #   - /app/${API_NAME}/node_modules  


networks:
  app_network:
    external: true
    
# for pkg in docker.io docker-doc docker-compose docker-compose-v2 podman-docker containerd runc; do sudo apt-get remove $pkg;
