version: "3"

x-default: &defaults
  networks: 
    - app_network
  env_file: 
    - ./.env

services: 
  jenkins: 
    container_name: my-jenkins-3
    image: ${JENKINS_IMG}
    privileged: true
    user: root
    ports:  
      - 2377:2376
      - 8083:8080
      - 50003:50000
    expose:
      - 8083

    <<: *defaults
    volumes: 
      - "jenkins_data:/var/jenkins_home"
      - "/var/run/docker.sock:/var/run/docker.sock"
    
volumes:
  jenkins_data:

networks:
  app_network:
    external: true
