version: "3"
services:

  web:
    container_name: web
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    restart: always
    ports:
      - 3000:3000
    networks:
      - default

  api:
    container_name: api
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    restart: always
    ports:
      - 3001:3001
    networks:
      - default

  db:
    image: postgres:alpine
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=mentorat
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=ikhela
    networks:
      - default

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
volumes:
  postgres_data:

networks:
  app_network:
    external: true
